language: python

python:
  - "3.5"
 
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "python ./setup.py develop"
# command to run tests
script: 
  - "flake8 --exclude=.virtualenv --ignore=E501"
  - "pylint openrazer"
  - "py.test --cov-report term-missing --cov=openrazer tests/"
 
after_success:
  coveralls

sudo: false
cache: pip
